# Generated by Django 5.2.5 on 2025-09-10 09:57

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Image must be 200px by 200px.', null='true', upload_to='avatars/', validators=[users.models.validate_avatar]),
        ),
    ]
