# Generated by Django 5.2.5 on 2025-09-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-featured', '-created_at']},
        ),
    ]
