# Generated by Django 5.2.5 on 2025-09-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_review_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamescore',
            old_name='settings',
            new_name='game_settings',
        ),
    ]
